import streamlit as st
import pandas as pd
import json
import plotly.graph_objects as go
from datetime import datetime
import os

# 페이지 설정
st.set_page_config(
    page_title="Hojun Lee | Master Dashboard",
    page_icon="🚀",
    layout="wide"
)

# --- 1. 사이드바 네비게이션 & 보안 설정 ---
st.sidebar.title("🌟 Hojun's Master Dashboard")

# URL 파라미터 확인 (?view=admin 일 때만 경력 메뉴 표시)
query_params = st.query_params
is_admin = query_params.get("view") == "admin"

menu_options = ["📊 삼성바이오 실적 분석", "🔬 AI 가상 연구소 동향"]
if is_admin:
    menu_options.append("📂 경력 모니터링 (비밀)")

page = st.sidebar.selectbox("메뉴를 선택하세요", menu_options)

st.sidebar.markdown("---")
st.sidebar.subheader("🌐 친구들에게 공유하기")
st.sidebar.info("""
1. 현재 보고 계신 웹 브라우저의 **URL 주소를 복사**하여 보내주세요.
2. 친구들은 '실적 분석'과 'AI 연구 동향'만 볼 수 있습니다.
""")

# --- 2. 페이지별 함수 정의 ---

def show_samsung_page():
    st.title("🚀 삼성바이오 실적 분석 대시보드")
    DATA_FILE = "samsung_historical_data.json"
    
    if not os.path.exists(DATA_FILE):
        st.error("데이터 파일을 찾을 수 없습니다.")
        return

    with open(DATA_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    # 삼성바이오로직스 섹션
    st.header("🏢 삼성바이오로직스 (Samsung Biologics)")
    biologics_df = pd.DataFrame(data["SamsungBiologics"])
    colors = ['#8EBAD9'] * (len(biologics_df) - 1) + ['#EB5E28']
    
    col1, col2 = st.columns([2, 1])
    with col1:
        fig1 = go.Figure()
        fig1.add_trace(go.Bar(x=biologics_df['period'], y=biologics_df['revenue'], name='매출액(십억)', marker_color=colors, text=biologics_df['revenue'], textposition='auto'))
        fig1.add_trace(go.Scatter(x=biologics_df['period'], y=biologics_df['op_income'], name='영업이익(십억)', mode='lines+markers+text', line=dict(color='#252422', width=3), text=biologics_df['op_income'], textposition='top center'))
        fig1.update_layout(title="분기별 매출 및 영업이익 추이", height=500)
        st.plotly_chart(fig1, use_container_width=True)
    with col2:
        st.subheader("💡 주요 인사이트")
        st.info("4공장 풀 가동 및 고부가가치 수주 확대로 사상 최대 매출 달성.")

    st.divider()

    # 삼성바이오에피스 섹션
    st.header("🧬 삼성바이오에피스 (Samsung Bioepis)")
    bioepis_df = pd.DataFrame(data["SamsungBioepis"])
    quarter_data = bioepis_df[bioepis_df['period'].str.contains('Q')]
    if not quarter_data.empty:
        fig2 = go.Figure()
        fig2.add_trace(go.Bar(x=quarter_data['period'], y=quarter_data['revenue'], name='매출액(십억)', marker_color='#B7E4C7', text=quarter_data['revenue'], textposition='auto'))
        fig2.update_layout(title="실적 추이 (바이오시밀러 글로벌 점유율 확대)", height=400)
        st.plotly_chart(fig2, use_container_width=True)

def show_ai_research_page():
    st.title("🔬 AI 에이전트 가상 연구소 전략 대시보드")
    HISTORY_FILE = "ai_research_history.json"
    IMAGE_FILE = "virtual_lab_infographic_v1.png"
    
    if not os.path.exists(HISTORY_FILE):
        st.warning("아직 수집된 연구 데이터가 없습니다. 서버에서 수집기를 가동해주세요.")
        return

    with open(HISTORY_FILE, 'r', encoding='utf-8') as f:
        history = json.load(f)
    
    latest = history[-1]
    st.header(f"🖼️ 이번 주 핵심 인포그래픽 ({latest['date']})")
    
    # 인포그래픽 표시 (파일 존재 여부 확인)
    if os.path.exists(IMAGE_FILE):
        st.image(IMAGE_FILE, use_container_width=True, caption="AI 에이전트 협업 구조 (Generated by AI)")
    else:
        st.info("🎨 인포그래픽 이미지를 생성 중이거나 경로를 확인 중입니다.")
    
    st.divider()
    st.header("📋 최신 논문 분석 & PPT 슬라이드")
    st.markdown(latest['analysis'])
    
    st.divider()
    st.header("📝 NotebookLM Expert Source")
    st.download_button("NotebookLM용 소스 다운로드", latest['analysis'], file_name=f"notebook_source_{latest['date']}.txt")

def show_career_page():
    st.title("📂 개인 경력 관리 (Secret Mode)")
    st.success("🔓 관리자 모드로 접속하셨습니다. 이 메뉴는 박사님께만 보입니다.")
    
    # 실제 경력 데이터 로드 로직 (있을 경우)
    st.markdown("### 최신 이직 기회 요약")
    if os.path.exists("seen_career_opportunities.json"):
        with open("seen_career_opportunities.json", "r", encoding="utf-8") as f:
            seen_jobs = json.load(f)
        st.write(f"현재까지 {len(seen_jobs)}개의 잠재적 기회를 탐색했습니다.")
    
    st.write("2주 단위 상세 리포트는 텔레그램을 통해 발송됩니다.")

# --- 3. 로직 실행 ---
if page == "📊 삼성바이오 실적 분석":
    show_samsung_page()
elif page == "🔬 AI 가상 연구소 동향":
    show_ai_research_page()
elif page == "📂 경력 모니터링 (비밀)":
    show_career_page()

st.sidebar.markdown("---")
st.sidebar.caption(f"Last updated: {datetime.now().strftime('%Y-%m-%d')}")
