import os
import json
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from datetime import datetime

class PPTXGenerator:
    def __init__(self, json_file):
        self.json_file = json_file
        
    def generate(self, target_date=None):
        if not os.path.exists(self.json_file):
            return None
            
        with open(self.json_file, 'r', encoding='utf-8') as f:
            history = json.load(f)
            
        if not history:
            return None
            
        # 선택한 날짜가 없으면 가장 최신 데이터 사용
        target_data = None
        if target_date:
            for item in history:
                if item.get('date') == target_date:
                    target_data = item
                    break
                    
        if not target_data:
            target_data = history[-1]
            
        prs = Presentation()
        
        # 1. 타이틀 슬라이드 (Cover)
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        
        title.text = "🔬 AI 가상 연구소 전략 브리핑"
        subtitle.text = f"Report Date: {target_data.get('date', datetime.now().strftime('%Y-%m-%d'))}\nGenerated by AI Agent"
        
        # 2. 최신 연구 논문 리스트 슬라이드
        bullet_slide_layout = prs.slide_layouts[1]
        slide2 = prs.slides.add_slide(bullet_slide_layout)
        title2 = slide2.shapes.title
        title2.text = "핵심 연구 동향 (Key Researches)"
        
        body_shape = slide2.shapes.placeholders[1]
        tf = body_shape.text_frame
        
        researches = target_data.get('researches', [])
        for i, r in enumerate(researches):
            p = tf.add_paragraph() if i > 0 else tf.paragraphs[0]
            p.text = f"[{r.get('journal', 'N/A')}] {r.get('title', '제목 없음')}"
            p.level = 0
            
            p_sub = tf.add_paragraph()
            p_sub.text = f"Link: {r.get('url', 'N/A')}"
            p_sub.level = 1
            
        # 3. AI 전략 분석 요약 슬라이드 (줄바꿈 단위로 끊어서)
        slide3 = prs.slides.add_slide(bullet_slide_layout)
        title3 = slide3.shapes.title
        title3.text = "전략적 시사점 및 분석"
        
        body_shape3 = slide3.shapes.placeholders[1]
        tf3 = body_shape3.text_frame
        
        analysis_text = target_data.get('analysis', '')
        # 간단한 마크다운 파싱 (##, -, * 등)
        lines = analysis_text.split('\n')
        
        first = True
        for line in lines:
            line = line.strip()
            if not line: continue
            
            p = tf3.add_paragraph() if not first else tf3.paragraphs[0]
            first = False
            
            # 텍스트 정리
            clean_line = line.replace('*', '').replace('#', '').strip()
            p.text = clean_line
            
            # 헤더 느낌이면 글씨를 키우고 레벨 0
            if line.startswith('##') or line.startswith('###'):
                p.level = 0
                p.font.bold = True
            elif line.startswith('-') or line.startswith('*'):
                p.level = 1
            else:
                p.level = 2

        # PPT 저장
        output_filename = f"AI_Research_Briefing_{target_data.get('date', 'latest')}.pptx"
        output_path = os.path.join(os.path.dirname(self.json_file), output_filename)
        prs.save(output_path)
        
        return output_path

if __name__ == "__main__":
    current_dir = os.path.dirname(os.path.abspath(__file__))
    json_path = os.path.join(current_dir, "ai_research_history.json")
    generator = PPTXGenerator(json_path)
    generator.generate()
    print("Test: PPTX generation completed.")
